//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IHffA7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filmscreenings
    {
        public int activityId { get; set; }
        public int filmId { get; set; }
        public int availableSeats { get; set; }
        public int roomId { get; set; }
    
        public virtual Activities Activities { get; set; }
        public virtual Films Films { get; set; }
        public virtual Rooms Rooms { get; set; }
    }
}
