//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IHffA7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservations
    {
        public int id { get; set; }
        public int wishlistId { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string paymentMethod { get; set; }
    
        public virtual Wishlists Wishlists { get; set; }
    }
}
