//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace IHffA7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservations
    {
        public int id { get; set; }

        public int wishlistId { get; set; }

        [Required]
        public string name { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        public string email { get; set; }

        [Required]
        public string paymentMethod { get; set; }
    
        public virtual Wishlists Wishlists { get; set; }
    }
}
