//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IHffA7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurants
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Restaurants()
        {
            this.Activities = new HashSet<Activities>();
        }
    
        public int id { get; set; }
        public string descriptionNL { get; set; }
        public string descriptionEN { get; set; }
        public System.DateTime lunchStart { get; set; }
        public System.DateTime lunchEnd { get; set; }
        public System.DateTime dinnerStart { get; set; }
        public System.DateTime dinnerEnd { get; set; }
        public string restaurantLogo { get; set; }
        public int locationId { get; set; }
    
        public virtual Locations Locations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activities> Activities { get; set; }
    }
}
