//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IHffA7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WishlistItems
    {
        public int id { get; set; }
        public int wishlistId { get; set; }
        public int activityId { get; set; }
        public int numberOfPersons { get; set; }
    
        public virtual Activities Activities { get; set; }
        public virtual Wishlists Wishlists { get; set; }
    }
}
